name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./order 관리/pom.xml
          mvn clean package -f ./delivery관리/pom.xml
          mvn clean package -f ./stock관리/pom.xml
          mvn clean package -f ./dashboard/pom.xml

      - name: Docker Build and push for Order관리
        uses: docker/build-push-action@v4
        with:
          context: ./order 관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order-관리:latest
            ghcr.io/${{ github.repository }}/order-관리:${{ github.ref_name }}
            
      - name: Docker Build and push for Delivery관리
        uses: docker/build-push-action@v4
        with:
          context: ./delivery관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery관리:latest
            ghcr.io/${{ github.repository }}/delivery관리:${{ github.ref_name }}
            
      - name: Docker Build and push for Stock관리
        uses: docker/build-push-action@v4
        with:
          context: ./stock관리
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/stock관리:latest
            ghcr.io/${{ github.repository }}/stock관리:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
