server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: order 관리
          uri: http://localhost:8082
          predicates:
            - Path=/orderDetails/**, 
        - id: delivery관리
          uri: http://localhost:8083
          predicates:
            - Path=/deliveryDetails/**, 
        - id: stock관리
          uri: http://localhost:8084
          predicates:
            - Path=/stockDetails/**, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, /mypages/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order 관리
          uri: http://order관리:8080
          predicates:
            - Path=/orderDetails/**, 
        - id: delivery관리
          uri: http://delivery관리:8080
          predicates:
            - Path=/deliveryDetails/**, 
        - id: stock관리
          uri: http://stock관리:8080
          predicates:
            - Path=/stockDetails/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
